name = input("Digite seu nome: \n")
idade = int(input("Digite sua idade: \n"))
profissao = input("Digite sua profissão: \n")
altura = float(input("Digite sua altura: \n"))
print("### Dados da Gabs ####")
print("====================")
print("Nome: ", name, "\nIdade: ", idade, "\nProfissão: ", profissao, "\nAltura: ", altura)